devices:
  adjust_period: 3
  capture:
    channels: 2
    device: BlackHole 2ch
    format: FLOAT32LE
    type: CoreAudio
  capture_samplerate: 48000
  chunksize: 1024
  enable_rate_adjust: false
  enable_resampling: true
  playback:
    channels: 2
    device: BT HIFI AUDIO
    format: FLOAT32LE
    type: CoreAudio
  queuelimit: 4
  resampler_type: FastAsync
  samplerate: 48000
  silence_threshold: 0
  silence_timeout: 0
  target_level: 1024
filters:
  New Filter 1:
    parameters:
      gain: 20
      inverted: false
      mute: false
    type: Gain
  biquad1:
    parameters:
      freq: 39.5
      gain: -6.8
      q: 4.283
      type: Peaking
    type: Biquad
  biquad2:
    parameters:
      freq: 52.5
      gain: -4.9
      q: 2
      type: Peaking
    type: Biquad
  biquad3:
    parameters:
      freq: 64.3
      gain: -6.8
      q: 12.129
      type: Peaking
    type: Biquad
  biquad4:
    parameters:
      freq: 80.2
      gain: -5.3
      q: 3.5
      type: Peaking
    type: Biquad
  biquad5:
    parameters:
      freq: 121.5
      gain: -10.5
      q: 4.304
      type: Peaking
    type: Biquad
  biquad6:
    parameters:
      freq: 366
      gain: -5.7
      q: 5
      type: Peaking
    type: Biquad
  volumeexample:
    parameters:
      ramp_time: 200
    type: Volume
mixers:
  New Mixer 1:
    channels:
      in: 2
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
pipeline:
- channel: 0
  names:
  - New Filter 1
  type: Filter
- channel: 0
  names:
  - volumeexample
  type: Filter
- channel: 0
  names:
  - biquad1
  - biquad2
  - biquad3
  - biquad4
  - biquad5
  - biquad6
  type: Filter
- channel: 1
  names:
  - New Filter 1
  type: Filter
- channel: 1
  names:
  - volumeexample
  type: Filter
- channel: 1
  names:
  - biquad1
  - biquad2
  - biquad3
  - biquad4
  - biquad5
  - biquad6
  type: Filter
